### ISSUE TITLE
给个歌单呗

### ISSUE THREAD

**Issue by Bonjir** [telecomadm1145/cmania#2]
没有songs (\*/ω＼\*)

**Comment by telecomadm1145** [comment]
osu.sayobot.cn 自己下载 osumania 谱面。
新建文件夹为songs并解压到其中

example:
Songs\114514 artist - title\xxx.osu

**Comment by telecomadm1145** [comment]
![图片](https://github.com/telecomadm1145/cmania/assets/47657299/25110db7-1cf6-4287-8221-17a9e727274d)
